version: "3.8"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    network_mode: "host"
    # ports:
    #   - "8080:8080" 
    env_file:
      - backend/.env
    environment:
      - SLURM_USER_NAME=${SLURM_USER_NAME}
      - SLURM_USER_TOKEN=${SLURM_USER_TOKEN}
      - SLURM_RESTD_IP=${SLURM_RESTD_IP}
      - SLURM_RESTD_PORT=${SLURM_RESTD_PORT}

  frontend:
    build:
      context: ./web
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - backend