AutoDetect=off

NodeName=gpu01 Name=gpu Type=v100 File=/dev/zero Flags=no_gpu_env
NodeName=gpu01 Name=gpu Type=v100 File=/dev/urandom Flags=no_gpu_env

NodeName=gpu02 Name=gpu Type=a100 File=/dev/zero Flags=no_gpu_env
NodeName=gpu02 Name=gpu Type=a100 File=/dev/urandom Flags=no_gpu_env

NodeName=gpu03 Name=gpu Type=h100 File=/dev/zero Flags=no_gpu_env
NodeName=gpu03 Name=gpu Type=h100 File=/dev/urandom Flags=no_gpu_env

NodeName=gpu04 Name=gpu Type=l40s File=/dev/zero Flags=no_gpu_env
NodeName=gpu04 Name=gpu Type=l40s File=/dev/urandom Flags=no_gpu_env

NodeName=gpu05 Name=gpu Type=mi250 File=/dev/zero Flags=no_gpu_env
NodeName=gpu05 Name=gpu Type=mi250 File=/dev/urandom Flags=no_gpu_env
