ClusterName=slurm-view-demo
SlurmctldHost=slurmctld(172.30.50.12)

AuthType=auth/munge
CredType=cred/munge
SlurmUser=slurm
SlurmdUser=root

SlurmctldPort=6817
SlurmdPort=6818
StateSaveLocation=/var/spool/slurmctld
SlurmdSpoolDir=/var/spool/slurmd
ReturnToService=2

CommunicationParameters=disable_http
SchedulerType=sched/backfill
SelectType=select/cons_tres
SelectTypeParameters=CR_Core_Memory
SlurmdParameters=config_overrides

ProctrackType=proctrack/cgroup
TaskPlugin=task/cgroup
JobAcctGatherType=jobacct_gather/cgroup
JobAcctGatherFrequency=5

AccountingStorageType=accounting_storage/slurmdbd
AccountingStorageHost=172.30.50.11
AccountingStoragePort=6819
AccountingStorageEnforce=associations

NodeName=cpu01 NodeAddr=172.30.50.21 CPUs=2 Boards=1 SocketsPerBoard=1 CoresPerSocket=2 ThreadsPerCore=1 RealMemory=1024 State=UNKNOWN
PartitionName=compute Nodes=cpu01 Default=YES MaxTime=INFINITE State=UP
