ClusterName=slurm-view-demo
SlurmctldHost=slurmctld(172.30.50.12)

AuthType=auth/munge
CredType=cred/munge
SlurmUser=slurm
SlurmdUser=root

SlurmctldPort=6817
SlurmdPort=6818
StateSaveLocation=/var/spool/slurmctld
SlurmdSpoolDir=/var/spool/slurmd
ReturnToService=2

CommunicationParameters=disable_http
SchedulerType=sched/backfill
SelectType=select/cons_tres
SelectTypeParameters=CR_Core_Memory
SlurmdParameters=config_overrides
GresTypes=gpu

PriorityType=priority/multifactor
PriorityWeightAge=1000
PriorityWeightFairshare=10000
PriorityWeightJobSize=1000
PriorityWeightPartition=1000
PriorityWeightQOS=5000

ProctrackType=proctrack/cgroup
TaskPlugin=task/cgroup
JobAcctGatherType=jobacct_gather/cgroup
JobAcctGatherFrequency=5

AccountingStorageType=accounting_storage/slurmdbd
AccountingStorageHost=172.30.50.11
AccountingStoragePort=6819
AccountingStorageEnforce=limits,qos
AccountingStorageTRES=gres/gpu,gres/gpu:a100

NodeName=cpu01 NodeAddr=172.30.50.21 CPUs=16 Boards=1 SocketsPerBoard=1 CoresPerSocket=16 ThreadsPerCore=1 RealMemory=64000 State=UNKNOWN
NodeName=cpu02 NodeAddr=172.30.50.22 CPUs=16 Boards=1 SocketsPerBoard=1 CoresPerSocket=16 ThreadsPerCore=1 RealMemory=64000 State=UNKNOWN
NodeName=cpu03 NodeAddr=172.30.50.23 CPUs=16 Boards=1 SocketsPerBoard=1 CoresPerSocket=16 ThreadsPerCore=1 RealMemory=64000 State=UNKNOWN
NodeName=cpu04 NodeAddr=172.30.50.24 CPUs=16 Boards=1 SocketsPerBoard=1 CoresPerSocket=16 ThreadsPerCore=1 RealMemory=64000 State=UNKNOWN
NodeName=cpu05 NodeAddr=172.30.50.25 CPUs=16 Boards=1 SocketsPerBoard=1 CoresPerSocket=16 ThreadsPerCore=1 RealMemory=64000 State=UNKNOWN
NodeName=cpu06 NodeAddr=172.30.50.26 CPUs=16 Boards=1 SocketsPerBoard=1 CoresPerSocket=16 ThreadsPerCore=1 RealMemory=64000 State=UNKNOWN
NodeName=cpu07 NodeAddr=172.30.50.27 CPUs=16 Boards=1 SocketsPerBoard=1 CoresPerSocket=16 ThreadsPerCore=1 RealMemory=64000 State=UNKNOWN
NodeName=cpu08 NodeAddr=172.30.50.28 CPUs=16 Boards=1 SocketsPerBoard=1 CoresPerSocket=16 ThreadsPerCore=1 RealMemory=64000 State=UNKNOWN
NodeName=highmem01 NodeAddr=172.30.50.29 CPUs=16 Boards=1 SocketsPerBoard=1 CoresPerSocket=16 ThreadsPerCore=1 RealMemory=128000 State=UNKNOWN
NodeName=highmem02 NodeAddr=172.30.50.30 CPUs=16 Boards=1 SocketsPerBoard=1 CoresPerSocket=16 ThreadsPerCore=1 RealMemory=128000 State=UNKNOWN
NodeName=gpu01 NodeAddr=172.30.50.31 CPUs=16 Boards=1 SocketsPerBoard=1 CoresPerSocket=16 ThreadsPerCore=1 RealMemory=128000 Gres=gpu:a100:2 State=UNKNOWN
NodeName=gpu02 NodeAddr=172.30.50.32 CPUs=16 Boards=1 SocketsPerBoard=1 CoresPerSocket=16 ThreadsPerCore=1 RealMemory=128000 Gres=gpu:a100:2 State=UNKNOWN

PartitionName=compute Nodes=cpu[01-08] Default=YES DefaultTime=00:20:00 MaxTime=01:00:00 State=UP DefMemPerCPU=4000
PartitionName=highmem Nodes=highmem[01-02] DefaultTime=00:20:00 MaxTime=01:00:00 State=UP DefMemPerCPU=8000
PartitionName=gpu Nodes=gpu[01-02] DefaultTime=00:20:00 MaxTime=01:00:00 State=UP DefMemPerCPU=8000
